/* Rebuild the complete offline manifest after adding scripts or artwork. */
'use strict';
const fs = require('node:fs');
const path = require('node:path');
const root = path.resolve(__dirname, '..');
const walk = dir => fs.readdirSync(path.join(root, dir), { withFileTypes: true })
  .flatMap(e => e.isDirectory() ? walk(`${dir}/${e.name}`) : [`${dir}/${e.name}`]);
const version = fs.readFileSync(path.join(root, 'js/util.js'), 'utf8').match(/G.VERSION = '([^']+)'/)[1];
const files = ['./', './index.html', './manifest.webmanifest', ...['css', 'js', 'assets'].flatMap(walk).sort().map(f => './' + f)];
const source = `/* Generated by node tools/build-cache.cjs. */
const CACHE = 'gloamreach-v${version}';
const FILES = ${JSON.stringify(files, null, 2)};
self.addEventListener('install', event => {
  event.waitUntil(caches.open(CACHE).then(cache => cache.addAll(FILES)).then(() => self.skipWaiting()));
});
self.addEventListener('activate', event => {
  event.waitUntil(caches.keys().then(keys => Promise.all(keys.filter(k => k.startsWith('gloamreach-') && k !== CACHE).map(k => caches.delete(k)))).then(() => self.clients.claim()));
});
self.addEventListener('fetch', event => {
  if (event.request.method !== 'GET' || new URL(event.request.url).origin !== self.location.origin) return;
  event.respondWith(fetch(event.request).then(response => {
    if (response.ok) {
      const copy = response.clone();
      event.waitUntil(caches.open(CACHE).then(cache => cache.put(event.request, copy)).catch(() => {}));
    }
    return response;
  }).catch(async () => {
    const cached = await caches.match(event.request);
    if (cached) return cached;
    if (event.request.mode === 'navigate') return (await caches.match('./index.html')) || Response.error();
    return Response.error();
  }));
});
`;
fs.writeFileSync(path.join(root, 'sw.js'), source);
console.log(`Offline cache ${version}: ${files.length} files`);
